#include "fanproc_fan.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void fanproc_fan_initialize(void);
void fanproc_fan_notify(microkit_channel channel);
void fanproc_fan_timeTriggered(void);

volatile sb_queue_CoolingFan_FanCmd_1_t *fanCmd_queue_1;
sb_queue_CoolingFan_FanCmd_1_Recv_t fanCmd_recv_queue;
volatile sb_queue_CoolingFan_FanAck_1_t *fanAck_queue_1;

#define PORT_FROM_MON 54

CoolingFan_FanCmd last_fanCmd_payload;

bool get_fanCmd(CoolingFan_FanCmd *data) {
  sb_event_counter_t numDropped;
  CoolingFan_FanCmd fresh_data;
  bool isFresh = sb_queue_CoolingFan_FanCmd_1_dequeue((sb_queue_CoolingFan_FanCmd_1_Recv_t *) &fanCmd_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_fanCmd_payload = fresh_data;
  }
  *data = last_fanCmd_payload;
  return isFresh;
}

bool put_fanAck(const CoolingFan_FanAck *data) {
  sb_queue_CoolingFan_FanAck_1_enqueue((sb_queue_CoolingFan_FanAck_1_t *) fanAck_queue_1, (CoolingFan_FanAck *) data);

  return true;
}

void init(void) {
  sb_queue_CoolingFan_FanCmd_1_Recv_init(&fanCmd_recv_queue, (sb_queue_CoolingFan_FanCmd_1_t *) fanCmd_queue_1);

  sb_queue_CoolingFan_FanAck_1_init((sb_queue_CoolingFan_FanAck_1_t *) fanAck_queue_1);

  fanproc_fan_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      fanproc_fan_timeTriggered();
      break;
    default:
      fanproc_fan_notify(channel);
  }
}
