"""
End-to-end promotion against the real CVM: a sanctioned AADL contract edit
is detected by the attestation-manager check, promoted (target maps
regenerated by syntax scan, gold moved, fresh goldens provisioned), and a
verification episode attests the live tree clean against the NEW baseline.

Runs on scratch copies of the protocol dirs and golden/; the live tree
carries the sanctioned edit for the duration and is restored to the
original baseline on teardown.

Auto-skipped unless CVM binary, asp-libs (extract_golden_slice),
temp-control-jvm, and golden/ are present.
"""

import shutil
import sys
from pathlib import Path

import pytest

from pybb import BlackboardController
from pybb.attestation import (
    CvmSubprocessClient,
    ProtocolDir,
    TargetSnapshot,
    attestation_request,
    make_attestation_predicate,
    make_promotion_predicate,
    make_provision_predicate,
    request_promotion,
)
from pybb.attestation.client import DEFAULT_ASP_BIN, DEFAULT_CVM_BINARY
from pybb.attestation.targetmap import TEMP_CONTROL_SPEC

sys.path.insert(0, str(Path(__file__).parent.parent / "examples"))
from attestation_manager import changed_contracts  # noqa: E402

FIXTURES = Path(__file__).parent / "fixtures"
GOLDEN_ROOT = Path(__file__).parent.parent / "golden"
TC_ROOT = Path("/Users/adampetz/Claude_workspace/temp-control-jvm")
PROTOCOL_IDS = ("gumbo_l1a", "gumbo_l1b", "gumbo_l2")

pytestmark = [
    pytest.mark.cvm,
    pytest.mark.skipif(
        not (
            Path(DEFAULT_CVM_BINARY).is_file()
            and (Path(DEFAULT_ASP_BIN) / "extract_golden_slice").is_file()
            and TC_ROOT.is_dir()
            and GOLDEN_ROOT.is_dir()
        ),
        reason="requires CVM binary, asp-libs, temp-control-jvm, and golden/",
    ),
]


@pytest.fixture
def sanctioned_edit():
    """Apply the SetPoint bound revision to the live model; restore after."""
    original = TargetSnapshot.load(
        {pid: ProtocolDir.load(str(FIXTURES / pid)) for pid in PROTOCOL_IDS},
        GOLDEN_ROOT,
    )
    aadl = TC_ROOT / "aadl/packages/TempControlSystem.aadl"
    aadl.write_text(aadl.read_text().replace('f32"110.0"', 'f32"112.0"', 1))
    try:
        yield aadl
    finally:
        original.restore()


def test_sanctioned_change_promoted_to_new_baseline(tmp_path, sanctioned_edit):
    golden_tmp = tmp_path / "golden"
    shutil.copytree(GOLDEN_ROOT, golden_tmp)
    protocols = {}
    for pid in PROTOCOL_IDS:
        shutil.copytree(FIXTURES / pid, tmp_path / pid)
        protocols[pid] = ProtocolDir.load(str(tmp_path / pid))

    # the AM's check: the revised invariant is detected, position-independently
    changed = changed_contracts(protocols)
    assert any("tc_sys_aadl_305_308" in t for t in changed), changed

    # promotion episode: promote request + provisioning requests, in order
    client = CvmSubprocessClient()
    ctl = BlackboardController()
    ctl.register_predicate("promotion", make_promotion_predicate(
        protocols, golden_tmp, TEMP_CONTROL_SPEC, codegen_fn=lambda: "noop"))
    ctl.register_predicate("provision", make_provision_predicate(
        client, protocols, golden_tmp))
    request_promotion(ctl.blackboard, "gumbo", list(PROTOCOL_IDS))
    bb = ctl.run()

    promo = bb.provision["promote:gumbo"]
    assert promo.good_standing, promo.result
    outcome = promo.result
    assert outcome.captured == 6
    # derived maps are complete supersets of the old curated ones
    assert outcome.targets["gumbo_l1a"] == 4
    assert outcome.targets["gumbo_l1b"] == 6
    assert outcome.targets["gumbo_l2"] > 22
    for pid in PROTOCOL_IDS:
        entry = bb.provision[f"provision:{pid}"]
        assert entry.good_standing, entry.result
    # the moved gold carries the revised bound
    from pybb.attestation.snapshot import mirror_path
    assert 'f32"112.0"' in mirror_path(golden_tmp, sanctioned_edit).read_text()

    # verification episode: live tree attests clean against the NEW baseline
    verifier = BlackboardController()
    verifier.register_predicate(
        "attestation", make_attestation_predicate(client, protocols))
    for key, start in (("gumbo:files", "gumbo_l1a"),
                       ("gumbo:contracts", "gumbo_l1b")):
        verifier.blackboard.write_entry(key=key, predicate="attestation",
                                        measurement=attestation_request(start))
        verifier.route(key, on_fail=[])
    bb2 = verifier.run()
    assert bb2.entries["gumbo:files"].good_standing
    assert bb2.entries["gumbo:contracts"].good_standing
    assert not bb2.escalate

    # and the AM's check now reports no pending changes against the new gold
    assert changed_contracts(protocols) == []
