#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool get_currentTemp(TempSensor_Temperature_i *data);
bool put_fanCmd(const CoolingFan_FanCmd *data);
bool get_setPoint(TempControlSystem_SetPoint_i *data);
bool get_fanAck(CoolingFan_FanAck *data);
