// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_currentTemp(value: *mut TempSensor::Temperature_i) -> bool;
  fn get_fanAck(value: *mut CoolingFan::FanAck) -> bool;
  fn get_setPoint(value: *mut TempControlSystem::SetPoint_i) -> bool;
  fn put_fanCmd(value: *mut CoolingFan::FanCmd) -> bool;
}

pub fn unsafe_get_currentTemp() -> TempSensor::Temperature_i
{
  unsafe {
    let value: *mut TempSensor::Temperature_i = &mut TempSensor::Temperature_i::default();
    get_currentTemp(value);
    return *value;
  }
}

pub fn unsafe_get_fanAck() -> CoolingFan::FanAck
{
  unsafe {
    let value: *mut CoolingFan::FanAck = &mut CoolingFan::FanAck::default();
    get_fanAck(value);
    return *value;
  }
}

pub fn unsafe_get_setPoint() -> TempControlSystem::SetPoint_i
{
  unsafe {
    let value: *mut TempControlSystem::SetPoint_i = &mut TempControlSystem::SetPoint_i::default();
    get_setPoint(value);
    return *value;
  }
}

pub fn unsafe_put_fanCmd(value: &CoolingFan::FanCmd) -> bool
{
  unsafe {
    return put_fanCmd(value as *const CoolingFan::FanCmd as *mut CoolingFan::FanCmd);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_currentTemp: Mutex<Option<TempSensor::Temperature_i>> = Mutex::new(None);
  pub static ref IN_fanAck: Mutex<Option<CoolingFan::FanAck>> = Mutex::new(None);
  pub static ref IN_setPoint: Mutex<Option<TempControlSystem::SetPoint_i>> = Mutex::new(None);
  pub static ref OUT_fanCmd: Mutex<Option<CoolingFan::FanCmd>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_currentTemp.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_fanAck.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_setPoint.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_fanCmd.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_currentTemp(value: *mut TempSensor::Temperature_i) -> bool
{
  unsafe {
    let guard = IN_currentTemp.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_fanAck(value: *mut CoolingFan::FanAck) -> bool
{
  unsafe {
    let guard = IN_fanAck.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_setPoint(value: *mut TempControlSystem::SetPoint_i) -> bool
{
  unsafe {
    let guard = IN_setPoint.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn put_fanCmd(value: *mut CoolingFan::FanCmd) -> bool
{
  unsafe {
    *OUT_fanCmd.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
