// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait tcproc_tempControl_Api {}

  pub trait tcproc_tempControl_Put_Api: tcproc_tempControl_Api {
    #[verifier::external_body]
    fn unverified_put_fanCmd(
      &mut self,
      value: CoolingFan::FanCmd)
    {
      extern_api::unsafe_put_fanCmd(&value);
    }
  }

  pub trait tcproc_tempControl_Get_Api: tcproc_tempControl_Api {
    #[verifier::external_body]
    fn unverified_get_currentTemp(
      &mut self,
      value: &Ghost<TempSensor::Temperature_i>) -> (res : TempSensor::Temperature_i)
      ensures
        res == value@,
        // assume currentTempInputRange
        (res.degrees >= -70i32) &&
          (res.degrees <= 180i32),
    {
      return extern_api::unsafe_get_currentTemp();
    }

    #[verifier::external_body]
    fn unverified_get_fanAck(
      &mut self,
      value: &Ghost<CoolingFan::FanAck>) -> (res : CoolingFan::FanAck)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_fanAck();
    }

    #[verifier::external_body]
    fn unverified_get_setPoint(
      &mut self,
      value: &Ghost<TempControlSystem::SetPoint_i>) -> (res : TempControlSystem::SetPoint_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_setPoint();
    }
  }

  pub trait tcproc_tempControl_Full_Api: tcproc_tempControl_Put_Api + tcproc_tempControl_Get_Api {}

  pub struct tcproc_tempControl_Application_Api<API: tcproc_tempControl_Api> {
    pub api: API,

    pub ghost currentTemp: TempSensor::Temperature_i,
    pub ghost fanAck: CoolingFan::FanAck,
    pub ghost setPoint: TempControlSystem::SetPoint_i,
    pub ghost fanCmd: CoolingFan::FanCmd
  }

  impl<API: tcproc_tempControl_Put_Api> tcproc_tempControl_Application_Api<API> {
    pub fn put_fanCmd(
      &mut self,
      value: CoolingFan::FanCmd)
      ensures
        old(self).currentTemp == self.currentTemp,
        old(self).fanAck == self.fanAck,
        old(self).setPoint == self.setPoint,
        self.fanCmd == value,
    {
      self.api.unverified_put_fanCmd(value);
      self.fanCmd = value;
    }
  }

  impl<API: tcproc_tempControl_Get_Api> tcproc_tempControl_Application_Api<API> {
    pub fn get_currentTemp(&mut self) -> (res : TempSensor::Temperature_i)
      ensures
        old(self).currentTemp == self.currentTemp,
        res == self.currentTemp,
        old(self).fanAck == self.fanAck,
        old(self).setPoint == self.setPoint,
        old(self).fanCmd == self.fanCmd,
        // assume currentTempInputRange
        (res.degrees >= -70i32) &&
          (res.degrees <= 180i32),
    {
      self.api.unverified_get_currentTemp(&Ghost(self.currentTemp))
    }
    pub fn get_fanAck(&mut self) -> (res : CoolingFan::FanAck)
      ensures
        old(self).currentTemp == self.currentTemp,
        old(self).fanAck == self.fanAck,
        res == self.fanAck,
        old(self).setPoint == self.setPoint,
        old(self).fanCmd == self.fanCmd,
    {
      self.api.unverified_get_fanAck(&Ghost(self.fanAck))
    }
    pub fn get_setPoint(&mut self) -> (res : TempControlSystem::SetPoint_i)
      ensures
        old(self).currentTemp == self.currentTemp,
        old(self).fanAck == self.fanAck,
        old(self).setPoint == self.setPoint,
        res == self.setPoint,
        old(self).fanCmd == self.fanCmd,
    {
      self.api.unverified_get_setPoint(&Ghost(self.setPoint))
    }
  }

  pub struct tcproc_tempControl_Initialization_Api;
  impl tcproc_tempControl_Api for tcproc_tempControl_Initialization_Api {}
  impl tcproc_tempControl_Put_Api for tcproc_tempControl_Initialization_Api {}

  pub const fn init_api() -> tcproc_tempControl_Application_Api<tcproc_tempControl_Initialization_Api> {
    return tcproc_tempControl_Application_Api {
      api: tcproc_tempControl_Initialization_Api {},

      currentTemp: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit },
      fanAck: CoolingFan::FanAck::Ok,
      setPoint: TempControlSystem::SetPoint_i { low: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit }, high: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit } },
      fanCmd: CoolingFan::FanCmd::On
    }
  }

  pub struct tcproc_tempControl_Compute_Api;
  impl tcproc_tempControl_Api for tcproc_tempControl_Compute_Api {}
  impl tcproc_tempControl_Put_Api for tcproc_tempControl_Compute_Api {}
  impl tcproc_tempControl_Get_Api for tcproc_tempControl_Compute_Api {}
  impl tcproc_tempControl_Full_Api for tcproc_tempControl_Compute_Api {}

  pub const fn compute_api() -> tcproc_tempControl_Application_Api<tcproc_tempControl_Compute_Api> {
    return tcproc_tempControl_Application_Api {
      api: tcproc_tempControl_Compute_Api {},

      currentTemp: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit },
      fanAck: CoolingFan::FanAck::Ok,
      setPoint: TempControlSystem::SetPoint_i { low: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit }, high: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit } },
      fanCmd: CoolingFan::FanCmd::On
    }
  }

}