// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Assm: Integration constraint on tempControl's incoming data port currentTemp
  *
  * assume currentTempInputRange
  */
pub fn I_Assm_currentTemp(currentTemp: TempSensor::Temperature_i) -> bool
{
  (currentTemp.degrees >= -70i32) &
    (currentTemp.degrees <= 180i32)
}

/** Initialize EntryPointContract
  *
  * guarantee initLatestFanCmd
  *   Initialize state variable
  * @param latestFanCmd post-state state variable
  */
pub fn initialize_initLatestFanCmd(latestFanCmd: CoolingFan::FanCmd) -> bool
{
  latestFanCmd == CoolingFan::FanCmd::Off
}

/** Initialize EntryPointContract
  *
  * guarantee initFanCmd
  *   Initial fan command
  * @param api_fanCmd outgoing data port
  */
pub fn initialize_initFanCmd(api_fanCmd: CoolingFan::FanCmd) -> bool
{
  api_fanCmd == CoolingFan::FanCmd::Off
}

/** IEP-Guar: Initialize Entrypoint for tempControl
  *
  * @param latestFanCmd post-state state variable
  * @param api_fanCmd outgoing data port
  */
pub fn initialize_IEP_Guar(
  latestFanCmd: CoolingFan::FanCmd,
  api_fanCmd: CoolingFan::FanCmd) -> bool
{
  initialize_initLatestFanCmd(latestFanCmd) &&
  initialize_initFanCmd(api_fanCmd)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param latestFanCmd post-state state variable
  * @param api_fanCmd outgoing data port
  */
pub fn initialize_IEP_Post(
  latestFanCmd: CoolingFan::FanCmd,
  api_fanCmd: CoolingFan::FanCmd) -> bool
{
  initialize_IEP_Guar(latestFanCmd, api_fanCmd)
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for tempControl
  *
  * @param In_latestFanCmd pre-state state variable
  * @param api_currentTemp incoming data port
  * @param api_fanAck incoming data port
  * @param api_setPoint incoming data port
  */
pub fn compute_CEP_Pre(
  In_latestFanCmd: CoolingFan::FanCmd,
  api_currentTemp: TempSensor::Temperature_i,
  api_fanAck: CoolingFan::FanAck,
  api_setPoint: TempControlSystem::SetPoint_i) -> bool
{
  // I-Assm-Guard: Integration constraints for tempControl's incoming ports
  let r0: bool = I_Assm_currentTemp(api_currentTemp);

  return r0;
}

/** Compute Entrypoint Contract
  *
  * guarantee altCurrentTempLTSetPoint
  *   If current temperature is less than
  *   the current low set point, then the fan state shall be Off
  * @param latestFanCmd post-state state variable
  * @param api_currentTemp incoming data port
  * @param api_setPoint incoming data port
  * @param api_fanCmd outgoing data port
  */
pub fn compute_spec_altCurrentTempLTSetPoint_guarantee(
  latestFanCmd: CoolingFan::FanCmd,
  api_currentTemp: TempSensor::Temperature_i,
  api_setPoint: TempControlSystem::SetPoint_i,
  api_fanCmd: CoolingFan::FanCmd) -> bool
{
  impliesL!(
    (api_currentTemp.degrees < api_setPoint.low.degrees),
    (latestFanCmd == CoolingFan::FanCmd::Off) &&
      (api_fanCmd == CoolingFan::FanCmd::Off))
}

/** Compute Entrypoint Contract
  *
  * guarantee altCurrentTempGTSetPoint
  *   If current temperature is greater than
  *   the current high set point, then the fan state shall be On
  * @param latestFanCmd post-state state variable
  * @param api_currentTemp incoming data port
  * @param api_setPoint incoming data port
  * @param api_fanCmd outgoing data port
  */
pub fn compute_spec_altCurrentTempGTSetPoint_guarantee(
  latestFanCmd: CoolingFan::FanCmd,
  api_currentTemp: TempSensor::Temperature_i,
  api_setPoint: TempControlSystem::SetPoint_i,
  api_fanCmd: CoolingFan::FanCmd) -> bool
{
  impliesL!(
    (api_currentTemp.degrees > api_setPoint.high.degrees),
    (latestFanCmd == CoolingFan::FanCmd::On) &
      (api_fanCmd == CoolingFan::FanCmd::On))
}

/** Compute Entrypoint Contract
  *
  * guarantee altCurrentTempInRange
  *   If current temperature is greater than or equal to the 
  *   current low set point and less than or equal to the current high set point, 
  *   then the current fan state is maintained.
  * @param In_latestFanCmd pre-state state variable
  * @param latestFanCmd post-state state variable
  * @param api_currentTemp incoming data port
  * @param api_setPoint incoming data port
  * @param api_fanCmd outgoing data port
  */
pub fn compute_spec_altCurrentTempInRange_guarantee(
  In_latestFanCmd: CoolingFan::FanCmd,
  latestFanCmd: CoolingFan::FanCmd,
  api_currentTemp: TempSensor::Temperature_i,
  api_setPoint: TempControlSystem::SetPoint_i,
  api_fanCmd: CoolingFan::FanCmd) -> bool
{
  implies!(
    (api_currentTemp.degrees >= api_setPoint.low.degrees) &
      (api_currentTemp.degrees <= api_setPoint.high.degrees),
    (latestFanCmd == In_latestFanCmd) &
      (api_fanCmd == latestFanCmd))
}

/** CEP-T-Guar: Top-level guarantee contracts for tempControl's compute entrypoint
  *
  * @param In_latestFanCmd pre-state state variable
  * @param latestFanCmd post-state state variable
  * @param api_currentTemp incoming data port
  * @param api_setPoint incoming data port
  * @param api_fanCmd outgoing data port
  */
pub fn compute_CEP_T_Guar(
  In_latestFanCmd: CoolingFan::FanCmd,
  latestFanCmd: CoolingFan::FanCmd,
  api_currentTemp: TempSensor::Temperature_i,
  api_setPoint: TempControlSystem::SetPoint_i,
  api_fanCmd: CoolingFan::FanCmd) -> bool
{
  let r0: bool = compute_spec_altCurrentTempLTSetPoint_guarantee(latestFanCmd, api_currentTemp, api_setPoint, api_fanCmd);
  let r1: bool = compute_spec_altCurrentTempGTSetPoint_guarantee(latestFanCmd, api_currentTemp, api_setPoint, api_fanCmd);
  let r2: bool = compute_spec_altCurrentTempInRange_guarantee(In_latestFanCmd, latestFanCmd, api_currentTemp, api_setPoint, api_fanCmd);

  return r0 && r1 && r2;
}

/** CEP-Post: Compute Entrypoint Post-Condition for tempControl
  *
  * @param In_latestFanCmd pre-state state variable
  * @param latestFanCmd post-state state variable
  * @param api_currentTemp incoming data port
  * @param api_fanAck incoming data port
  * @param api_setPoint incoming data port
  * @param api_fanCmd outgoing data port
  */
pub fn compute_CEP_Post(
  In_latestFanCmd: CoolingFan::FanCmd,
  latestFanCmd: CoolingFan::FanCmd,
  api_currentTemp: TempSensor::Temperature_i,
  api_fanAck: CoolingFan::FanAck,
  api_setPoint: TempControlSystem::SetPoint_i,
  api_fanCmd: CoolingFan::FanCmd) -> bool
{
  // CEP-Guar: guarantee clauses of tempControl's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(In_latestFanCmd, latestFanCmd, api_currentTemp, api_setPoint, api_fanCmd);

  return r0;
}
