// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn put_currentTemp(value: *mut TempSensor::Temperature_i) -> bool;
}

pub fn unsafe_put_currentTemp(value: &TempSensor::Temperature_i) -> bool
{
  unsafe {
    return put_currentTemp(value as *const TempSensor::Temperature_i as *mut TempSensor::Temperature_i);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref OUT_currentTemp: Mutex<Option<TempSensor::Temperature_i>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *OUT_currentTemp.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn put_currentTemp(value: *mut TempSensor::Temperature_i) -> bool
{
  unsafe {
    *OUT_currentTemp.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
