// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Guar: Integration constraint on tempSensor's outgoing data port currentTemp
  *
  * guarantee currentTempOutputRange
  */
pub fn I_Guar_currentTemp(currentTemp: TempSensor::Temperature_i) -> bool
{
  (currentTemp.degrees >= -50i32) &
    (currentTemp.degrees <= 150i32)
}

/** Initialize EntryPointContract
  *
  * guarantee currentTempInitialVal
  * @param api_currentTemp outgoing data port
  */
pub fn initialize_currentTempInitialVal(api_currentTemp: TempSensor::Temperature_i) -> bool
{
  api_currentTemp.degrees == 72i32
}

/** IEP-Guar: Initialize Entrypoint for tempSensor
  *
  * @param api_currentTemp outgoing data port
  */
pub fn initialize_IEP_Guar(api_currentTemp: TempSensor::Temperature_i) -> bool
{
  initialize_currentTempInitialVal(api_currentTemp)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_currentTemp outgoing data port
  */
pub fn initialize_IEP_Post(api_currentTemp: TempSensor::Temperature_i) -> bool
{
  // I-Guar-Guard: Integration constraints for tempSensor's outgoing ports"
  I_Guar_currentTemp(api_currentTemp)&& 

  initialize_IEP_Guar(api_currentTemp)
}

/** CEP-Post: Compute Entrypoint Post-Condition for tempSensor
  *
  * @param api_currentTemp outgoing data port
  */
pub fn compute_CEP_Post(api_currentTemp: TempSensor::Temperature_i) -> bool
{
  // I-Guar-Guard: Integration constraints for tempSensor's outgoing ports
  let r0: bool = I_Guar_currentTemp(api_currentTemp);

  return r0;
}
