// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait tsproc_tempSensor_Api {}

  pub trait tsproc_tempSensor_Put_Api: tsproc_tempSensor_Api {
    #[verifier::external_body]
    fn unverified_put_currentTemp(
      &mut self,
      value: TempSensor::Temperature_i)
    {
      extern_api::unsafe_put_currentTemp(&value);
    }
  }

  pub trait tsproc_tempSensor_Get_Api: tsproc_tempSensor_Api {
  }

  pub trait tsproc_tempSensor_Full_Api: tsproc_tempSensor_Put_Api + tsproc_tempSensor_Get_Api {}

  pub struct tsproc_tempSensor_Application_Api<API: tsproc_tempSensor_Api> {
    pub api: API,

    pub ghost currentTemp: TempSensor::Temperature_i
  }

  impl<API: tsproc_tempSensor_Put_Api> tsproc_tempSensor_Application_Api<API> {
    pub fn put_currentTemp(
      &mut self,
      value: TempSensor::Temperature_i)
      requires
        // guarantee currentTempOutputRange
        (value.degrees >= -50i32) &&
          (value.degrees <= 150i32),
      ensures
        self.currentTemp == value,
    {
      self.api.unverified_put_currentTemp(value);
      self.currentTemp = value;
    }
  }

  impl<API: tsproc_tempSensor_Get_Api> tsproc_tempSensor_Application_Api<API> {
  }

  pub struct tsproc_tempSensor_Initialization_Api;
  impl tsproc_tempSensor_Api for tsproc_tempSensor_Initialization_Api {}
  impl tsproc_tempSensor_Put_Api for tsproc_tempSensor_Initialization_Api {}

  pub const fn init_api() -> tsproc_tempSensor_Application_Api<tsproc_tempSensor_Initialization_Api> {
    return tsproc_tempSensor_Application_Api {
      api: tsproc_tempSensor_Initialization_Api {},

      currentTemp: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit }
    }
  }

  pub struct tsproc_tempSensor_Compute_Api;
  impl tsproc_tempSensor_Api for tsproc_tempSensor_Compute_Api {}
  impl tsproc_tempSensor_Put_Api for tsproc_tempSensor_Compute_Api {}
  impl tsproc_tempSensor_Get_Api for tsproc_tempSensor_Compute_Api {}
  impl tsproc_tempSensor_Full_Api for tsproc_tempSensor_Compute_Api {}

  pub const fn compute_api() -> tsproc_tempSensor_Application_Api<tsproc_tempSensor_Compute_Api> {
    return tsproc_tempSensor_Application_Api {
      api: tsproc_tempSensor_Compute_Api {},

      currentTemp: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit }
    }
  }

}