// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

use super::TempSensor::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct SetPoint_i {
    pub low: Temperature_i,
    pub high: Temperature_i
  }

  impl Default for SetPoint_i {
    fn default() -> Self
    {
      Self { low: TempSensor::Temperature_i::default(), high: TempSensor::Temperature_i::default() }
    }
  }

}