#include "oiproc_operatorInterface.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void oiproc_operatorInterface_initialize(void);
void oiproc_operatorInterface_notify(microkit_channel channel);
void oiproc_operatorInterface_timeTriggered(void);

volatile sb_queue_TempSensor_Temperature_i_1_t *currentTemp_queue_1;
sb_queue_TempSensor_Temperature_i_1_Recv_t currentTemp_recv_queue;
volatile sb_queue_TempControlSystem_SetPoint_i_1_t *setPoint_queue_1;

#define PORT_FROM_MON 56

TempSensor_Temperature_i last_currentTemp_payload;

bool get_currentTemp(TempSensor_Temperature_i *data) {
  sb_event_counter_t numDropped;
  TempSensor_Temperature_i fresh_data;
  bool isFresh = sb_queue_TempSensor_Temperature_i_1_dequeue((sb_queue_TempSensor_Temperature_i_1_Recv_t *) &currentTemp_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_currentTemp_payload = fresh_data;
  }
  *data = last_currentTemp_payload;
  return isFresh;
}

bool put_setPoint(const TempControlSystem_SetPoint_i *data) {
  sb_queue_TempControlSystem_SetPoint_i_1_enqueue((sb_queue_TempControlSystem_SetPoint_i_1_t *) setPoint_queue_1, (TempControlSystem_SetPoint_i *) data);

  return true;
}

void init(void) {
  sb_queue_TempSensor_Temperature_i_1_Recv_init(&currentTemp_recv_queue, (sb_queue_TempSensor_Temperature_i_1_t *) currentTemp_queue_1);

  sb_queue_TempControlSystem_SetPoint_i_1_init((sb_queue_TempControlSystem_SetPoint_i_1_t *) setPoint_queue_1);

  oiproc_operatorInterface_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      oiproc_operatorInterface_timeTriggered();
      break;
    default:
      oiproc_operatorInterface_notify(channel);
  }
}
