// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_currentTemp: TempSensor::Temperature_i
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_currentTemp(container.api_currentTemp);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(currentTemp: TempSensor::Temperature_i)
{
  put_currentTemp(currentTemp);
}

/// setter for IN DataPort
pub fn put_currentTemp(value: TempSensor::Temperature_i)
{
  *extern_api::IN_currentTemp.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// getter for OUT DataPort
pub fn get_setPoint() -> TempControlSystem::SetPoint_i
{
  return extern_api::OUT_setPoint.lock().unwrap_or_else(|e| e.into_inner()).expect("Not expecting None")
}
