// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

/// default proptest strategy for i32: any value of the type
pub fn i32_strategy_default() -> impl Strategy<Value = i32>
{
  any::<i32>()
}

/// custom proptest strategy for i32 restricted to an inclusive range
pub fn i32_strategy_cust(range: core::ops::RangeInclusive<i32>) -> impl Strategy<Value = i32>
{
  range
}

pub fn TempSensor_TempUnit_strategy_default() -> impl Strategy<Value = TempSensor::TempUnit>
{
  TempSensor_TempUnit_strategy_cust(1, 1, 1)
}

pub fn TempSensor_TempUnit_strategy_cust(
  Fahrenheit_bias: u32,
  Celsius_bias: u32,
  Kelvin_bias: u32) -> impl Strategy<Value = TempSensor::TempUnit>
{
  prop_oneof![
    Fahrenheit_bias => Just(TempSensor::TempUnit::Fahrenheit),
    Celsius_bias => Just(TempSensor::TempUnit::Celsius),
    Kelvin_bias => Just(TempSensor::TempUnit::Kelvin)
  ]
}

pub fn CoolingFan_FanAck_strategy_default() -> impl Strategy<Value = CoolingFan::FanAck>
{
  CoolingFan_FanAck_strategy_cust(1, 1)
}

pub fn CoolingFan_FanAck_strategy_cust(
  Ok_bias: u32,
  Error_bias: u32) -> impl Strategy<Value = CoolingFan::FanAck>
{
  prop_oneof![
    Ok_bias => Just(CoolingFan::FanAck::Ok),
    Error_bias => Just(CoolingFan::FanAck::Error)
  ]
}

pub fn CoolingFan_FanCmd_strategy_default() -> impl Strategy<Value = CoolingFan::FanCmd>
{
  CoolingFan_FanCmd_strategy_cust(1, 1)
}

pub fn CoolingFan_FanCmd_strategy_cust(
  On_bias: u32,
  Off_bias: u32) -> impl Strategy<Value = CoolingFan::FanCmd>
{
  prop_oneof![
    On_bias => Just(CoolingFan::FanCmd::On),
    Off_bias => Just(CoolingFan::FanCmd::Off)
  ]
}

/// default proptest strategy for bool: any value of the type
pub fn bool_strategy_default() -> impl Strategy<Value = bool>
{
  any::<bool>()
}

pub fn TempSensor_Temperature_i_strategy_default() -> impl Strategy<Value = TempSensor::Temperature_i>
{
  TempSensor_Temperature_i_strategy_cust(
    any::<i32>(),
    TempSensor_TempUnit_strategy_default()
  )
}

pub fn TempSensor_Temperature_i_strategy_cust
  <degrees_i32_strategy: Strategy<Value = i32>, 
   unit_TempSensor_TempUnit_strategy: Strategy<Value = TempSensor::TempUnit>> (
  degrees_strategy: degrees_i32_strategy,
  unit_strategy: unit_TempSensor_TempUnit_strategy) -> impl Strategy<Value = TempSensor::Temperature_i>
{
  (degrees_strategy, unit_strategy).prop_map(|(degrees, unit)| {
    TempSensor::Temperature_i { degrees, unit }
  })
}

pub fn TempControlSystem_SetPoint_i_strategy_default() -> impl Strategy<Value = TempControlSystem::SetPoint_i>
{
  TempControlSystem_SetPoint_i_strategy_cust(
    TempSensor_Temperature_i_strategy_default(),
    TempSensor_Temperature_i_strategy_default()
  )
}

pub fn TempControlSystem_SetPoint_i_strategy_cust
  <low_TempSensor_Temperature_i_strategy: Strategy<Value = TempSensor::Temperature_i>, 
   high_TempSensor_Temperature_i_strategy: Strategy<Value = TempSensor::Temperature_i>> (
  low_strategy: low_TempSensor_Temperature_i_strategy,
  high_strategy: high_TempSensor_Temperature_i_strategy) -> impl Strategy<Value = TempControlSystem::SetPoint_i>
{
  (low_strategy, high_strategy).prop_map(|(low, high)| {
    TempControlSystem::SetPoint_i { low, high }
  })
}
