// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_fanCmd: CoolingFan::FanCmd
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_fanCmd(container.api_fanCmd);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(fanCmd: CoolingFan::FanCmd)
{
  put_fanCmd(fanCmd);
}

/// setter for IN DataPort
pub fn put_fanCmd(value: CoolingFan::FanCmd)
{
  *extern_api::IN_fanCmd.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// getter for OUT DataPort
pub fn get_fanAck() -> CoolingFan::FanAck
{
  return extern_api::OUT_fanAck.lock().unwrap_or_else(|e| e.into_inner()).expect("Not expecting None")
}
