#include <stdint.h>
#include <microkit.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#define PORT_TO_TSPROC_TEMPSENSOR_MON 61
#define PORT_TO_TCPROC_TEMPCONTROL_MON 59
#define PORT_TO_OIPROC_OPERATORINTERFACE_MON 57
#define PORT_TO_FANPROC_FAN_MON 55

void init(void) {}

void notified(microkit_channel channel) {
  switch(channel) {
    case PORT_TO_TSPROC_TEMPSENSOR_MON:
      microkit_notify(PORT_TO_TSPROC_TEMPSENSOR_MON);
      break;
    case PORT_TO_TCPROC_TEMPCONTROL_MON:
      microkit_notify(PORT_TO_TCPROC_TEMPCONTROL_MON);
      break;
    case PORT_TO_OIPROC_OPERATORINTERFACE_MON:
      microkit_notify(PORT_TO_OIPROC_OPERATORINTERFACE_MON);
      break;
    case PORT_TO_FANPROC_FAN_MON:
      microkit_notify(PORT_TO_FANPROC_FAN_MON);
      break;
  }
}
