#include "tcproc_tempControl.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void tcproc_tempControl_initialize(void);
void tcproc_tempControl_notify(microkit_channel channel);
void tcproc_tempControl_timeTriggered(void);

volatile sb_queue_TempSensor_Temperature_i_1_t *currentTemp_queue_1;
sb_queue_TempSensor_Temperature_i_1_Recv_t currentTemp_recv_queue;
volatile sb_queue_CoolingFan_FanCmd_1_t *fanCmd_queue_1;
volatile sb_queue_TempControlSystem_SetPoint_i_1_t *setPoint_queue_1;
sb_queue_TempControlSystem_SetPoint_i_1_Recv_t setPoint_recv_queue;
volatile sb_queue_CoolingFan_FanAck_1_t *fanAck_queue_1;
sb_queue_CoolingFan_FanAck_1_Recv_t fanAck_recv_queue;

#define PORT_FROM_MON 58

TempSensor_Temperature_i last_currentTemp_payload;

bool get_currentTemp(TempSensor_Temperature_i *data) {
  sb_event_counter_t numDropped;
  TempSensor_Temperature_i fresh_data;
  bool isFresh = sb_queue_TempSensor_Temperature_i_1_dequeue((sb_queue_TempSensor_Temperature_i_1_Recv_t *) &currentTemp_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_currentTemp_payload = fresh_data;
  }
  *data = last_currentTemp_payload;
  return isFresh;
}

bool put_fanCmd(const CoolingFan_FanCmd *data) {
  sb_queue_CoolingFan_FanCmd_1_enqueue((sb_queue_CoolingFan_FanCmd_1_t *) fanCmd_queue_1, (CoolingFan_FanCmd *) data);

  return true;
}

TempControlSystem_SetPoint_i last_setPoint_payload;

bool get_setPoint(TempControlSystem_SetPoint_i *data) {
  sb_event_counter_t numDropped;
  TempControlSystem_SetPoint_i fresh_data;
  bool isFresh = sb_queue_TempControlSystem_SetPoint_i_1_dequeue((sb_queue_TempControlSystem_SetPoint_i_1_Recv_t *) &setPoint_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_setPoint_payload = fresh_data;
  }
  *data = last_setPoint_payload;
  return isFresh;
}

CoolingFan_FanAck last_fanAck_payload;

bool get_fanAck(CoolingFan_FanAck *data) {
  sb_event_counter_t numDropped;
  CoolingFan_FanAck fresh_data;
  bool isFresh = sb_queue_CoolingFan_FanAck_1_dequeue((sb_queue_CoolingFan_FanAck_1_Recv_t *) &fanAck_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_fanAck_payload = fresh_data;
  }
  *data = last_fanAck_payload;
  return isFresh;
}

void init(void) {
  sb_queue_TempSensor_Temperature_i_1_Recv_init(&currentTemp_recv_queue, (sb_queue_TempSensor_Temperature_i_1_t *) currentTemp_queue_1);

  sb_queue_CoolingFan_FanCmd_1_init((sb_queue_CoolingFan_FanCmd_1_t *) fanCmd_queue_1);

  sb_queue_TempControlSystem_SetPoint_i_1_Recv_init(&setPoint_recv_queue, (sb_queue_TempControlSystem_SetPoint_i_1_t *) setPoint_queue_1);

  sb_queue_CoolingFan_FanAck_1_Recv_init(&fanAck_recv_queue, (sb_queue_CoolingFan_FanAck_1_t *) fanAck_queue_1);

  tcproc_tempControl_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      tcproc_tempControl_timeTriggered();
      break;
    default:
      tcproc_tempControl_notify(channel);
  }
}
