#pragma once

#include <stdbool.h>
#include <stdint.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

typedef
  enum {Fahrenheit, Celsius, Kelvin} TempSensor_TempUnit;

typedef
  enum {Ok, Error} CoolingFan_FanAck;

typedef
  enum {On, Off} CoolingFan_FanCmd;

typedef struct TempSensor_Temperature_i {
  int32_t degrees;
  TempSensor_TempUnit unit;
} TempSensor_Temperature_i;

typedef struct TempControlSystem_SetPoint_i {
  TempSensor_Temperature_i low;
  TempSensor_Temperature_i high;
} TempControlSystem_SetPoint_i;
