#pragma once

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <sb_aadl_types.h>
#include <sb_queue_TempSensor_Temperature_i_1.h>
#include <sb_queue_CoolingFan_FanCmd_1.h>
#include <sb_queue_TempControlSystem_SetPoint_i_1.h>
#include <sb_queue_CoolingFan_FanAck_1.h>
