// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::tcproc_tempControl_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::tcproc_tempControl_initialize();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let latestFanCmd = get_latestFanCmd();
  let api_fanCmd = get_fanCmd();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::initialize_IEP_Post (latestFanCmd, api_fanCmd) {
    return HarnessResult::FailedPostcondition(
      TestCaseError::Fail("Postcondition failed: incorrect output behavior".into())
    );
  }

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_currentTemp incoming data port
  * @param api_fanAck incoming data port
  * @param api_setPoint incoming data port
  */
pub fn testComputeCB(
  api_currentTemp: TempSensor::Temperature_i,
  api_fanAck: CoolingFan::FanAck,
  api_setPoint: TempControlSystem::SetPoint_i) -> HarnessResult
{
  // Initialize the app
  crate::tcproc_tempControl_initialize();

  // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved
  //                from the component state
  let In_latestFanCmd: CoolingFan::FanCmd = get_latestFanCmd();

  // [CheckPre]: check/filter based on pre-condition.
  if !GUMBOX::compute_CEP_Pre (In_latestFanCmd, api_currentTemp, api_fanAck, api_setPoint) {
    return HarnessResult::RejectedPrecondition;
  }

  // [PutInPorts]: Set values on the input ports
  put_currentTemp(api_currentTemp);
  put_fanAck(api_fanAck);
  put_setPoint(api_setPoint);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::tcproc_tempControl_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let latestFanCmd = get_latestFanCmd();
  let api_fanCmd = get_fanCmd();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_latestFanCmd, latestFanCmd, api_currentTemp, api_fanAck, api_setPoint, api_fanCmd) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_currentTemp, container.api_fanAck, container.api_setPoint)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_currentTemp: $api_currentTemp_strat:expr,
    api_fanAck: $api_fanAck_strat:expr,
    api_setPoint: $api_setPoint_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_currentTemp, api_fanAck, api_setPoint)
            in ($api_currentTemp_strat, $api_fanAck_strat, $api_setPoint_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_currentTemp, api_fanAck, api_setPoint) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param In_latestFanCmd pre-state state variable
  * @param api_currentTemp incoming data port
  * @param api_fanAck incoming data port
  * @param api_setPoint incoming data port
  */
pub fn testComputeCBwGSV(
  In_latestFanCmd: CoolingFan::FanCmd,
  api_currentTemp: TempSensor::Temperature_i,
  api_fanAck: CoolingFan::FanAck,
  api_setPoint: TempControlSystem::SetPoint_i) -> HarnessResult
{
  // Initialize the app
  crate::tcproc_tempControl_initialize();

  // [CheckPre]: check/filter based on pre-condition.
  if !GUMBOX::compute_CEP_Pre (In_latestFanCmd, api_currentTemp, api_fanAck, api_setPoint) {
    return HarnessResult::RejectedPrecondition;
  }

  // [PutInPorts]: Set values on the input ports
  put_currentTemp(api_currentTemp);
  put_fanAck(api_fanAck);
  put_setPoint(api_setPoint);

  // [SetInStateVars]: set the pre-state values of state variables
  put_latestFanCmd(In_latestFanCmd);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::tcproc_tempControl_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let latestFanCmd = get_latestFanCmd();
  let api_fanCmd = get_fanCmd();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_latestFanCmd, latestFanCmd, api_currentTemp, api_fanAck, api_setPoint, api_fanCmd) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCBwGSV_container(container: PreStateContainer_wGSV) -> HarnessResult
{
  return testComputeCBwGSV(container.In_latestFanCmd, container.api_currentTemp, container.api_fanAck, container.api_setPoint)
}

#[macro_export]
macro_rules!
testComputeCBwGSV_macro {
  (
    $test_name: ident,
    config: $config:expr,
    In_latestFanCmd: $In_latestFanCmd_strat:expr,
    api_currentTemp: $api_currentTemp_strat:expr,
    api_fanAck: $api_fanAck_strat:expr,
    api_setPoint: $api_setPoint_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (In_latestFanCmd, api_currentTemp, api_fanAck, api_setPoint)
            in ($In_latestFanCmd_strat, $api_currentTemp_strat, $api_fanAck_strat, $api_setPoint_strat)
      ) {
        match $crate::test::util::cb_apis::testComputeCBwGSV(In_latestFanCmd, api_currentTemp, api_fanAck, api_setPoint) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
