// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_currentTemp: TempSensor::Temperature_i,
  pub api_fanAck: CoolingFan::FanAck,
  pub api_setPoint: TempControlSystem::SetPoint_i
}

/// container for component's incoming port values and GUMBO state variables
pub struct PreStateContainer_wGSV {
  pub In_latestFanCmd: CoolingFan::FanCmd,
  pub api_currentTemp: TempSensor::Temperature_i,
  pub api_fanAck: CoolingFan::FanAck,
  pub api_setPoint: TempControlSystem::SetPoint_i
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_currentTemp(container.api_currentTemp);
  put_fanAck(container.api_fanAck);
  put_setPoint(container.api_setPoint);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_container_wGSV(container: PreStateContainer_wGSV)
{
  put_latestFanCmd(container.In_latestFanCmd);
  put_currentTemp(container.api_currentTemp);
  put_fanAck(container.api_fanAck);
  put_setPoint(container.api_setPoint);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  currentTemp: TempSensor::Temperature_i,
  fanAck: CoolingFan::FanAck,
  setPoint: TempControlSystem::SetPoint_i)
{
  put_currentTemp(currentTemp);
  put_fanAck(fanAck);
  put_setPoint(setPoint);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_wGSV(
  In_latestFanCmd: CoolingFan::FanCmd,
  currentTemp: TempSensor::Temperature_i,
  fanAck: CoolingFan::FanAck,
  setPoint: TempControlSystem::SetPoint_i)
{
  put_latestFanCmd(In_latestFanCmd);
  put_currentTemp(currentTemp);
  put_fanAck(fanAck);
  put_setPoint(setPoint);
}

/// setter for IN DataPort
pub fn put_currentTemp(value: TempSensor::Temperature_i)
{
  *extern_api::IN_currentTemp.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN DataPort
pub fn put_fanAck(value: CoolingFan::FanAck)
{
  *extern_api::IN_fanAck.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN DataPort
pub fn put_setPoint(value: TempControlSystem::SetPoint_i)
{
  *extern_api::IN_setPoint.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// getter for OUT DataPort
pub fn get_fanCmd() -> CoolingFan::FanCmd
{
  return extern_api::OUT_fanCmd.lock().unwrap_or_else(|e| e.into_inner()).expect("Not expecting None")
}

/// getter for GUMBO State Variable
pub fn get_latestFanCmd() -> CoolingFan::FanCmd
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.latestFanCmd,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_latestFanCmd(value: CoolingFan::FanCmd)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.latestFanCmd = value,
      None => panic!("The app is None")
    }
  }
}
