# Do not edit this file as it will be overwritten if HAMR codegen is rerun

MICROKIT_TOOL ?= $(MICROKIT_SDK)/bin/microkit

CFLAGS := -mcpu=$(CPU) \
	-mstrict-align \
	-ffreestanding \
	-nostdlib \
	-g3 \
	-O3 \
	-Wall -Wno-unused-function -Werror -Wno-unused-command-line-argument \
	-I$(MICROKIT_BOARD_DIR)/include \
	-target $(TARGET)

LDFLAGS := -L$(MICROKIT_BOARD_DIR)/lib
LIBS := --start-group -lmicrokit -Tmicrokit.ld --end-group

MSD ?= microkit.system

IMAGES := tsproc_tempSensor.elf tsproc_tempSensor_MON.elf tcproc_tempControl.elf tcproc_tempControl_MON.elf oiproc_operatorInterface.elf oiproc_operatorInterface_MON.elf fanproc_fan.elf fanproc_fan_MON.elf pacer.elf
IMAGE_FILE = loader.img
REPORT_FILE = report.txt

UTIL_OBJS = printf.o util.o

TYPES_DIR = $(TOP_DIR)/types
TYPE_OBJS := $(TOP_DIR)/build/sb_queue_TempSensor_Temperature_i_1.o $(TOP_DIR)/build/sb_queue_CoolingFan_FanCmd_1.o $(TOP_DIR)/build/sb_queue_TempControlSystem_SetPoint_i_1.o $(TOP_DIR)/build/sb_queue_CoolingFan_FanAck_1.o

# exporting TOP_TYPES_INCLUDE in case other makefiles need it
export TOP_TYPES_INCLUDE = -I$(TYPES_DIR)/include

TOP_INCLUDE = $(TOP_TYPES_INCLUDE) -I$(TOP_DIR)/util/include

all: $(IMAGE_FILE)
	CHECK_FLAGS_BOARD_MD5:=.board_cflags-$(shell echo -- ${CFLAGS} ${MICROKIT_BOARD} ${MICROKIT_CONFIG}| shasum | sed 's/ *-//')

${CHECK_FLAGS_BOARD_MD5}:
	-rm -f .board_cflags-*
	touch $@

%.o: ${TOP_DIR}/util/src/%.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_DIR)/util/include

$(TOP_DIR)/build/sb_queue_TempSensor_Temperature_i_1.o: $(TOP_DIR)/types/src/sb_queue_TempSensor_Temperature_i_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_CoolingFan_FanCmd_1.o: $(TOP_DIR)/types/src/sb_queue_CoolingFan_FanCmd_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_TempControlSystem_SetPoint_i_1.o: $(TOP_DIR)/types/src/sb_queue_TempControlSystem_SetPoint_i_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_CoolingFan_FanAck_1.o: $(TOP_DIR)/types/src/sb_queue_CoolingFan_FanAck_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


# monitor
tsproc_tempSensor_MON.o: $(TOP_DIR)/components/tsproc_tempSensor/src/tsproc_tempSensor_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/tsproc_tempSensor/include

# user code
tsproc_tempSensor_rust:
	make -C ${CRATES_DIR}/tsproc_tempSensor $(RUST_MAKE_TARGET)

tsproc_tempSensor.o: $(TOP_DIR)/components/tsproc_tempSensor/src/tsproc_tempSensor.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/tsproc_tempSensor/include

# monitor
tcproc_tempControl_MON.o: $(TOP_DIR)/components/tcproc_tempControl/src/tcproc_tempControl_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/tcproc_tempControl/include

# user code
tcproc_tempControl_rust:
	make -C ${CRATES_DIR}/tcproc_tempControl $(RUST_MAKE_TARGET)

tcproc_tempControl.o: $(TOP_DIR)/components/tcproc_tempControl/src/tcproc_tempControl.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/tcproc_tempControl/include

# monitor
oiproc_operatorInterface_MON.o: $(TOP_DIR)/components/oiproc_operatorInterface/src/oiproc_operatorInterface_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/oiproc_operatorInterface/include

# user code
oiproc_operatorInterface_rust:
	make -C ${CRATES_DIR}/oiproc_operatorInterface $(RUST_MAKE_TARGET)

oiproc_operatorInterface.o: $(TOP_DIR)/components/oiproc_operatorInterface/src/oiproc_operatorInterface.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/oiproc_operatorInterface/include

# monitor
fanproc_fan_MON.o: $(TOP_DIR)/components/fanproc_fan/src/fanproc_fan_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/fanproc_fan/include

# user code
fanproc_fan_rust:
	make -C ${CRATES_DIR}/fanproc_fan $(RUST_MAKE_TARGET)

fanproc_fan.o: $(TOP_DIR)/components/fanproc_fan/src/fanproc_fan.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/fanproc_fan/include

pacer.o: $(TOP_DIR)/components/pacer/src/pacer.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_INCLUDE)

tsproc_tempSensor_MON.elf: tsproc_tempSensor_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

tsproc_tempSensor.elf: $(UTIL_OBJS) $(TYPE_OBJS) tsproc_tempSensor_rust tsproc_tempSensor.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/tsproc_tempSensor/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -ltsproc_tempSensor -o $@

tcproc_tempControl_MON.elf: tcproc_tempControl_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

tcproc_tempControl.elf: $(UTIL_OBJS) $(TYPE_OBJS) tcproc_tempControl_rust tcproc_tempControl.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/tcproc_tempControl/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -ltcproc_tempControl -o $@

oiproc_operatorInterface_MON.elf: oiproc_operatorInterface_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

oiproc_operatorInterface.elf: $(UTIL_OBJS) $(TYPE_OBJS) oiproc_operatorInterface_rust oiproc_operatorInterface.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/oiproc_operatorInterface/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -loiproc_operatorInterface -o $@

fanproc_fan_MON.elf: fanproc_fan_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

fanproc_fan.elf: $(UTIL_OBJS) $(TYPE_OBJS) fanproc_fan_rust fanproc_fan.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/fanproc_fan/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lfanproc_fan -o $@

pacer.elf: $(UTIL_OBJS) $(TYPE_OBJS) pacer.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

$(IMAGE_FILE): $(IMAGES) $(TOP_DIR)/$(MSD)
	xmllint --xinclude $(TOP_DIR)/$(MSD) | awk 'FNR==1{print; print "<!--"; print "  DO NOT EDIT: This file is generated by merging"; print "    $(TOP_DIR)/$(MSD)"; print "  and its xi:included files."; print "  Modify the source files and run make instead."; print "-->"; next}1' > $(TOP_BUILD_DIR)/$(MSD).merged
	$(MICROKIT_TOOL) $(TOP_BUILD_DIR)/$(MSD).merged --search-path $(TOP_BUILD_DIR) --board $(MICROKIT_BOARD) --config $(MICROKIT_CONFIG) -o $(IMAGE_FILE) -r $(REPORT_FILE)


qemu:
	$(QEMU) -machine virt,virtualization=on \
			-cpu cortex-a53 \
			-serial mon:stdio \
			-device loader,file=$(IMAGE_FILE),addr=0x70000000,cpu-num=0 \
			-m size=2G \
			-nographic

clean::
	rm -f *.o

test:: 
	make -C ${CRATES_DIR}/tsproc_tempSensor test
	make -C ${CRATES_DIR}/tcproc_tempControl test
	make -C ${CRATES_DIR}/oiproc_operatorInterface test
	make -C ${CRATES_DIR}/fanproc_fan test

clean:: 
	make -C ${CRATES_DIR}/tsproc_tempSensor clean
	make -C ${CRATES_DIR}/tcproc_tempControl clean
	make -C ${CRATES_DIR}/oiproc_operatorInterface clean
	make -C ${CRATES_DIR}/fanproc_fan clean

verus: 
	make -C ${CRATES_DIR}/tsproc_tempSensor verus
	make -C ${CRATES_DIR}/tcproc_tempControl verus
	make -C ${CRATES_DIR}/oiproc_operatorInterface verus
	make -C ${CRATES_DIR}/fanproc_fan verus
