#include "tsproc_tempSensor.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void tsproc_tempSensor_initialize(void);
void tsproc_tempSensor_notify(microkit_channel channel);
void tsproc_tempSensor_timeTriggered(void);

volatile sb_queue_TempSensor_Temperature_i_1_t *currentTemp_queue_1;

#define PORT_FROM_MON 60

bool put_currentTemp(const TempSensor_Temperature_i *data) {
  sb_queue_TempSensor_Temperature_i_1_enqueue((sb_queue_TempSensor_Temperature_i_1_t *) currentTemp_queue_1, (TempSensor_Temperature_i *) data);

  return true;
}

void init(void) {
  sb_queue_TempSensor_Temperature_i_1_init((sb_queue_TempSensor_Temperature_i_1_t *) currentTemp_queue_1);

  tsproc_tempSensor_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      tsproc_tempSensor_timeTriggered();
      break;
    default:
      tsproc_tempSensor_notify(channel);
  }
}
