// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Copy, Clone, Debug, PartialEq, Eq)]
  pub enum TempUnit {
    pub Fahrenheit = 0,
    pub Celsius = 1,
    pub Kelvin = 2,
  }

  impl Default for TempUnit {
    fn default() -> Self
    {
      TempUnit::Fahrenheit
    }
  }

}