// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct Temperature_i {
    pub degrees: i32,
    pub unit: TempUnit
  }

  impl Default for Temperature_i {
    fn default() -> Self
    {
      Self { degrees: 0, unit: TempSensor::TempUnit::default() }
    }
  }

}