// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_currentTemp(value: *mut TempSensor::Temperature_i) -> bool;
  fn put_setPoint(value: *mut TempControlSystem::SetPoint_i) -> bool;
}

pub fn unsafe_get_currentTemp() -> TempSensor::Temperature_i
{
  unsafe {
    let value: *mut TempSensor::Temperature_i = &mut TempSensor::Temperature_i::default();
    get_currentTemp(value);
    return *value;
  }
}

pub fn unsafe_put_setPoint(value: &TempControlSystem::SetPoint_i) -> bool
{
  unsafe {
    return put_setPoint(value as *const TempControlSystem::SetPoint_i as *mut TempControlSystem::SetPoint_i);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_currentTemp: Mutex<Option<TempSensor::Temperature_i>> = Mutex::new(None);
  pub static ref OUT_setPoint: Mutex<Option<TempControlSystem::SetPoint_i>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_currentTemp.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_setPoint.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_currentTemp(value: *mut TempSensor::Temperature_i) -> bool
{
  unsafe {
    let guard = IN_currentTemp.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn put_setPoint(value: *mut TempControlSystem::SetPoint_i) -> bool
{
  unsafe {
    *OUT_setPoint.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
