// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait oiproc_operatorInterface_Api {}

  pub trait oiproc_operatorInterface_Put_Api: oiproc_operatorInterface_Api {
    #[verifier::external_body]
    fn unverified_put_setPoint(
      &mut self,
      value: TempControlSystem::SetPoint_i)
    {
      extern_api::unsafe_put_setPoint(&value);
    }
  }

  pub trait oiproc_operatorInterface_Get_Api: oiproc_operatorInterface_Api {
    #[verifier::external_body]
    fn unverified_get_currentTemp(
      &mut self,
      value: &Ghost<TempSensor::Temperature_i>) -> (res : TempSensor::Temperature_i)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_currentTemp();
    }
  }

  pub trait oiproc_operatorInterface_Full_Api: oiproc_operatorInterface_Put_Api + oiproc_operatorInterface_Get_Api {}

  pub struct oiproc_operatorInterface_Application_Api<API: oiproc_operatorInterface_Api> {
    pub api: API,

    pub ghost currentTemp: TempSensor::Temperature_i,
    pub ghost setPoint: TempControlSystem::SetPoint_i
  }

  impl<API: oiproc_operatorInterface_Put_Api> oiproc_operatorInterface_Application_Api<API> {
    pub fn put_setPoint(
      &mut self,
      value: TempControlSystem::SetPoint_i)
      ensures
        old(self).currentTemp == self.currentTemp,
        self.setPoint == value,
    {
      self.api.unverified_put_setPoint(value);
      self.setPoint = value;
    }
  }

  impl<API: oiproc_operatorInterface_Get_Api> oiproc_operatorInterface_Application_Api<API> {
    pub fn get_currentTemp(&mut self) -> (res : TempSensor::Temperature_i)
      ensures
        old(self).currentTemp == self.currentTemp,
        res == self.currentTemp,
        old(self).setPoint == self.setPoint,
    {
      self.api.unverified_get_currentTemp(&Ghost(self.currentTemp))
    }
  }

  pub struct oiproc_operatorInterface_Initialization_Api;
  impl oiproc_operatorInterface_Api for oiproc_operatorInterface_Initialization_Api {}
  impl oiproc_operatorInterface_Put_Api for oiproc_operatorInterface_Initialization_Api {}

  pub const fn init_api() -> oiproc_operatorInterface_Application_Api<oiproc_operatorInterface_Initialization_Api> {
    return oiproc_operatorInterface_Application_Api {
      api: oiproc_operatorInterface_Initialization_Api {},

      currentTemp: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit },
      setPoint: TempControlSystem::SetPoint_i { low: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit }, high: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit } }
    }
  }

  pub struct oiproc_operatorInterface_Compute_Api;
  impl oiproc_operatorInterface_Api for oiproc_operatorInterface_Compute_Api {}
  impl oiproc_operatorInterface_Put_Api for oiproc_operatorInterface_Compute_Api {}
  impl oiproc_operatorInterface_Get_Api for oiproc_operatorInterface_Compute_Api {}
  impl oiproc_operatorInterface_Full_Api for oiproc_operatorInterface_Compute_Api {}

  pub const fn compute_api() -> oiproc_operatorInterface_Application_Api<oiproc_operatorInterface_Compute_Api> {
    return oiproc_operatorInterface_Application_Api {
      api: oiproc_operatorInterface_Compute_Api {},

      currentTemp: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit },
      setPoint: TempControlSystem::SetPoint_i { low: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit }, high: TempSensor::Temperature_i { degrees: 0, unit: TempSensor::TempUnit::Fahrenheit } }
    }
  }

}