// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_fanCmd(value: *mut CoolingFan::FanCmd) -> bool;
  fn put_fanAck(value: *mut CoolingFan::FanAck) -> bool;
}

pub fn unsafe_get_fanCmd() -> CoolingFan::FanCmd
{
  unsafe {
    let value: *mut CoolingFan::FanCmd = &mut CoolingFan::FanCmd::default();
    get_fanCmd(value);
    return *value;
  }
}

pub fn unsafe_put_fanAck(value: &CoolingFan::FanAck) -> bool
{
  unsafe {
    return put_fanAck(value as *const CoolingFan::FanAck as *mut CoolingFan::FanAck);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_fanCmd: Mutex<Option<CoolingFan::FanCmd>> = Mutex::new(None);
  pub static ref OUT_fanAck: Mutex<Option<CoolingFan::FanAck>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_fanCmd.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_fanAck.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_fanCmd(value: *mut CoolingFan::FanCmd) -> bool
{
  unsafe {
    let guard = IN_fanCmd.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn put_fanAck(value: *mut CoolingFan::FanAck) -> bool
{
  unsafe {
    *OUT_fanAck.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
