// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait fanproc_fan_Api {}

  pub trait fanproc_fan_Put_Api: fanproc_fan_Api {
    #[verifier::external_body]
    fn unverified_put_fanAck(
      &mut self,
      value: CoolingFan::FanAck)
    {
      extern_api::unsafe_put_fanAck(&value);
    }
  }

  pub trait fanproc_fan_Get_Api: fanproc_fan_Api {
    #[verifier::external_body]
    fn unverified_get_fanCmd(
      &mut self,
      value: &Ghost<CoolingFan::FanCmd>) -> (res : CoolingFan::FanCmd)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_fanCmd();
    }
  }

  pub trait fanproc_fan_Full_Api: fanproc_fan_Put_Api + fanproc_fan_Get_Api {}

  pub struct fanproc_fan_Application_Api<API: fanproc_fan_Api> {
    pub api: API,

    pub ghost fanCmd: CoolingFan::FanCmd,
    pub ghost fanAck: CoolingFan::FanAck
  }

  impl<API: fanproc_fan_Put_Api> fanproc_fan_Application_Api<API> {
    pub fn put_fanAck(
      &mut self,
      value: CoolingFan::FanAck)
      ensures
        old(self).fanCmd == self.fanCmd,
        self.fanAck == value,
    {
      self.api.unverified_put_fanAck(value);
      self.fanAck = value;
    }
  }

  impl<API: fanproc_fan_Get_Api> fanproc_fan_Application_Api<API> {
    pub fn get_fanCmd(&mut self) -> (res : CoolingFan::FanCmd)
      ensures
        old(self).fanCmd == self.fanCmd,
        res == self.fanCmd,
        old(self).fanAck == self.fanAck,
    {
      self.api.unverified_get_fanCmd(&Ghost(self.fanCmd))
    }
  }

  pub struct fanproc_fan_Initialization_Api;
  impl fanproc_fan_Api for fanproc_fan_Initialization_Api {}
  impl fanproc_fan_Put_Api for fanproc_fan_Initialization_Api {}

  pub const fn init_api() -> fanproc_fan_Application_Api<fanproc_fan_Initialization_Api> {
    return fanproc_fan_Application_Api {
      api: fanproc_fan_Initialization_Api {},

      fanCmd: CoolingFan::FanCmd::On,
      fanAck: CoolingFan::FanAck::Ok
    }
  }

  pub struct fanproc_fan_Compute_Api;
  impl fanproc_fan_Api for fanproc_fan_Compute_Api {}
  impl fanproc_fan_Put_Api for fanproc_fan_Compute_Api {}
  impl fanproc_fan_Get_Api for fanproc_fan_Compute_Api {}
  impl fanproc_fan_Full_Api for fanproc_fan_Compute_Api {}

  pub const fn compute_api() -> fanproc_fan_Application_Api<fanproc_fan_Compute_Api> {
    return fanproc_fan_Application_Api {
      api: fanproc_fan_Compute_Api {},

      fanCmd: CoolingFan::FanCmd::On,
      fanAck: CoolingFan::FanAck::Ok
    }
  }

}